language: go
os:
  - linux
go:
  - '1.12'
script:
  - go test ./... -cover -coverprofile=coverage.out
notifications:
  slack:
    rooms:
      - levpay:zFXMmpOIs9amuhu3olE4mNGt
    on_success: never
    on_failure: always